//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_ban_hang.home.load_danh_muc.tim_kiem
{


    public partial class Tim_kiem_tenSP_gan_dung
    {

        /// <summary>
        /// list_load_sp_theo_danh_muc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal list_load_sp_theo_danh_muc;
    }
}
